version: "3"

services:
  db:
    container_name: db
    image: mongo:4.2
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    networks:
      - actualNetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: api
    networks:
      - actualNetwork
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - actualNetwork
    environment:
      WAIT_HOSTS: db:27017, api:5000

networks:
  actualNetwork:
