version: "3"

services:
  db:
    container_name: db
    image: mongo:4.2
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    networks:
      - actualNetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  api:
    build: .
    container_name: api
    ports:
      - 80:5000
    networks:
      - actualNetwork
    depends_on:
      - db

networks:
  actualNetwork:
